##配置端口号，字符集
server:
  port: 13145
  tomcat:
    uri-encoding: UTF-8
##配置数据库url，密码，用户名
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hookmedb?characterEncoding=utf8
    username: root
    password: 123456
#    url: jdbc:mysql://39.108.53.124:3306/hookmedb?characterEncoding=utf8
#    username: root
#    password: mysql675919
##thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
##配置jpa
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update